### ISSUE TITLE
Ejercicios equipo 6

### ISSUE THREAD

**Issue by JoseRodriguez-23620213** [SistemasTecTlaxiaco/actividad-2-ejercicios-equipo-6#2]
[Converciones.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-ejercicios-equipo-6/files/12582039/Converciones.pdf)

**Comment by josealfredo79** [comment]
Falta la calificación...

**Comment by 00Asaf00** [comment]
Portada: 80%
Procedimiento: 70%
Figuras-Ilustraciones-Fotografías: 40%
Resultados y conclusiones: 30%

Calificación: 0.2*55 = 12

**Comment by josealfredo79** [comment]
Revisado..

**Comment by Alberto796** [comment]
portada:22%
procedimiento:22%
figuras:17%
resultados:15%
calificaion:15.2
